services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ../nginx/:/etc/nginx/conf.d/:ro
      - ../certbot/www/:/var/www/certbot/:ro
    networks:
      - default-network
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/app/certbot/www/:/var/www/certbot/:rw
      - /etc/app/certbot/conf/:/etc/letsencrypt/:rw

networks:
  default-network:
    external: true
