name: GitHub Workflow

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    uses: BrunoBrasolin/workflow-template/.github/workflows/nginx.yml@main
    secrets: inherit
